

- name: Create an OSAD multi region cloud in OS Clouds
  hosts: localhost
  connection: local
  gather_facts: false
  user: root
  tasks:
    - name: launch an instance
      nova_compute:
        name: "{{ login_username }}-{{ region_name }}-{{ item }}"
        state: present
        login_username: "{{ login_username }}"
        login_password: "{{ login_password }}"
        login_tenant_name: "{{ login_tenant_name }}"
        auth_url: "{{ auth_url }}"
        region_name: "{{ region_name | capitalize }}"
        image_name: Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
        flavor_ram: 8192
        flavor_include: Performance
        key_name: "{{ os_keyname }}"
      with_items:
        - Identity
        - RegionOne
        - RegionTwo
      register: nova_hosts
      tags:
        - setup-identity
        - setup-hosts
        - setup-regions
        - setup
    - name: Load inventory
      add_host:
        hostname: "{{ item.info.name.split('-')[-1] }}"
        ansible_ssh_host: "{{ item.info.accessIPv4 }}"
        ansible_ssh_port: "22"
        groups: os_nodes
      with_items: nova_hosts.results
      tags:
        - setup-identity
        - setup-hosts
        - setup-regions
        - setup
    - name: Wait for ssh
      wait_for:
        port: 22
        host: "{{ item.info.accessIPv4 }}"
        search_regex: OpenSSH
        delay: 10
      with_items: nova_hosts.results
      tags:
        - setup-identity
        - setup-hosts
        - setup-regions
        - setup
  vars:
    login_username: "{{ os_username }}"
    login_password: "{{ os_password }}"
    login_tenant_name: "{{ os_tenant_name }}"
    region_name: "{{ os_region_name }}"
    auth_url: "{{ os_auth_url | default('https://identity.api.rackspacecloud.com/v2.0/') }}"


- name: Setup hosts
  hosts: os_nodes
  gather_facts: false
  user: root
  tasks:
    - name: Install base packages
      apt:
        name: "{{ item }}"
        update_cache: "yes"
        cache_valid_time: "3600"
      with_items:
        - vim
        - tmux
        - git
        - curl
      tags:
        - setup-hosts
    - name: Clone OSAD into place
      git:
        repo: "{{ git_repo }}"
        dest: /opt/os-ansible-deployment
        update: yes
        force: yes
      failed_when: false
      tags:
        - setup-hosts
    - name: Bootstrap ansible Ansible
      command: scripts/bootstrap-ansible.sh
      args:
        chdir: /opt/os-ansible-deployment
        creates: /usr/local/bin/openstack-ansible
      tags:
        - setup-hosts
    - name: Bootstrap ansible AIO
      command: scripts/bootstrap-aio.sh
      args:
        chdir: /opt/os-ansible-deployment
        creates: /etc/openstack_deploy/openstack_user_config.yml
      tags:
        - setup-hosts
  vars:
    git_repo: "{{ osad_repo | default('https://github.com/stackforge/os-ansible-deployment') }}"


- name: Setup Identity Hosts
  hosts: "Identity"
  gather_facts: false
  user: root
  tasks:
    - name: remove bootstrapped openstack_user_config
      file:
        path: /etc/openstack_deploy/conf.d/swift.yml
        state: absent
      tags:
        - setup-identity
        - identity-config
    - name: Replace user config
      template:
        src: templates/openstack_user_config_identity.yml.j2
        dest: /etc/openstack_deploy/openstack_user_config.yml
      tags:
        - setup-identity
        - identity-config
    - name: Drop user config file
      template:
        src: templates/identity.yml.j2
        dest: /etc/openstack_deploy/conf.d/identity.yml
      tags:
        - setup-identity
        - identity-config
    - name: Drop user keystone config file
      template:
        src: templates/user_region_identity.yml.j2
        dest: /etc/openstack_deploy/user_region_identity.yml
      tags:
        - setup-identity
        - identity-config
    - name: Run playbooks identity
      command: "openstack-ansible {{ item }}"
      args:
        chdir: /opt/os-ansible-deployment/playbooks
      with_items:
        - "setup-hosts.yml"
        - "haproxy-install.yml"
        - "repo-server.yml"
        - "repo-build.yml"
        - "memcached-install.yml"
        - "galera-install.yml"
        - "rabbitmq-install.yml"
        - "utility-install.yml"
        - "rsyslog-install.yml"
      tags:
        - setup-identity
    - name: Run keystone playbook
      command: openstack-ansible os-keystone-install.yml
      args:
        chdir: /opt/os-ansible-deployment/playbooks
      register: playbook_run
      until: playbook_run|success
      retries: 2
      delay: 1
      tags:
        - setup-identity
        - run-keystone
    - name: Run horizon playbook
      command: openstack-ansible os-horizon-install.yml
      args:
        chdir: /opt/os-ansible-deployment/playbooks
      register: playbook_run
      until: playbook_run|success
      retries: 2
      delay: 1
      tags:
        - setup-identity
        - run-horizon
  vars:
    login_username: "{{ os_username }}"
    region_name: "{{ os_region_name }}"


- name: Setup Regional Hosts
  hosts: os_nodes:!Identity
  gather_facts: false
  user: root
  tasks:
    - name: Replace user config
      template:
        src: templates/openstack_user_config_region.yml.j2
        dest: /etc/openstack_deploy/openstack_user_config.yml
      tags:
        - setup-regions
        - regional-config
    - name: Drop user keystone config file
      template:
        src: templates/user_identity.yml.j2
        dest: /etc/openstack_deploy/user_identity.yml
      tags:
        - setup-regions
        - regional-config
    - name: Drop user region one config file
      template:
        src: templates/user_region_one.yml.j2
        dest: /etc/openstack_deploy/user_region_one.yml
      when: inventory_hostname == "RegionOne"
      delegate_to: "RegionOne"
      tags:
        - setup-regions
        - regional-config
    - name: Drop regional swift config file
      template:
        src: templates/openstack_user_config_swift.yml.j2
        dest: /etc/openstack_deploy/conf.d/swift.yml
      tags:
        - setup-regions
        - regional-config
    - name: Drop user region two config file
      template:
        src: templates/user_region_two.yml.j2
        dest: /etc/openstack_deploy/user_region_two.yml
      when: inventory_hostname == "RegionTwo"
      delegate_to: "RegionTwo"
      tags:
        - setup-regions
        - regional-config
    - name: Drop user config file
      template:
        src: templates/region.yml.j2
        dest: /etc/openstack_deploy/conf.d/region.yml
      tags:
        - setup-regions
        - regional-config
    - name: Get OS creds
      command: >
        grep -e '^cinder' \
             -e '^glance' \
             -e '^heat' \
             -e '^keystone' \
             -e '^neutron' \
             -e '^nova' \
             -e '^swift' \
             /etc/openstack_deploy/user_secrets.yml
      register: keystone_secrets
      delegate_to: Identity
      no_log: True
      tags:
        - setup-regions
        - regional-config
    - name: Set keystone credentials
      lineinfile:
        dest: /etc/openstack_deploy/user_secrets.yml
        regexp: '^{{ item.split()[1] }}'
        line: "{{ item }}"
      with_items: keystone_secrets.stdout_lines
      no_log: True
      tags:
        - setup-regions
        - regional-config
    - name: Run regional playbooks
      command: "openstack-ansible {{ item }}"
      args:
        chdir: /opt/os-ansible-deployment/playbooks
      with_items:
        - "setup-hosts.yml"
        - "haproxy-install.yml"
        - "memcached-install.yml"
        - "galera-install.yml"
        - "rabbitmq-install.yml"
        - "utility-install.yml"
        - "rsyslog-install.yml"
      tags:
        - setup-regions
    - name: Run Swift playbook
      command: openstack-ansible os-swift-install.yml
      args:
        chdir: /opt/os-ansible-deployment/playbooks
      register: playbook_run
      until: playbook_run|success
      retries: 2
      delay: 1
      tags:
        - setup-regions
        - run-swift
    - name: Run glance playbook
      command: openstack-ansible os-glance-install.yml
      args:
        chdir: /opt/os-ansible-deployment/playbooks
      register: playbook_run
      until: playbook_run|success
      retries: 2
      delay: 1
      tags:
        - setup-regions
        - run-glance
    - name: Run cinder playbook
      command: openstack-ansible os-cinder-install.yml
      args:
        chdir: /opt/os-ansible-deployment/playbooks
      register: playbook_run
      until: playbook_run|success
      retries: 2
      delay: 1
      tags:
        - setup-regions
        - run-cinder
    - name: Run nova playbook
      command: openstack-ansible os-nova-install.yml
      args:
        chdir: /opt/os-ansible-deployment/playbooks
      register: playbook_run
      until: playbook_run|success
      retries: 2
      delay: 1
      tags:
        - setup-regions
        - run-nova
    - name: Run neutron playbook
      command: openstack-ansible os-neutron-install.yml
      args:
        chdir: /opt/os-ansible-deployment/playbooks
      register: playbook_run
      until: playbook_run|success
      retries: 2
      delay: 1
      tags:
        - setup-regions
        - run-neutron
    - name: Run heat playbook
      command: openstack-ansible os-heat-install.yml
      args:
        chdir: /opt/os-ansible-deployment/playbooks
      register: playbook_run
      until: playbook_run|success
      retries: 2
      delay: 1
      tags:
        - setup-regions
        - run-heat
